name: Java CI

on: [push]

jobs:
  build-linux-jdk8-fx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install xvfb
    - name: Build with Ant
      run: xvfb-run ant test-javase
      
  build-windows-jdk8-fx:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Build with Ant
      env:
        ANT_PATH: ant
      run: ant test-javase
  
  build-windows-jdk11-fx:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk+fx
    - name: Build with Ant
      env:
        ANT_PATH: ant
      run: ant test-javase
 
  build-windows-jdk11-nofx:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
    - name: Build with Ant
      env:
        ANT_PATH: ant
      run: ant test-javase
  
  build-mac-jdk8-fx:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: "Install Ant"
      run: brew install ant
    - name: Build with Ant
      env:
        ANT_PATH: ant
      run: ant test-javase
  
  build-mac-jdk11-fx:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk+fx
    - name: "Install Ant"
      run: brew install ant
    - name: Build with Ant
      env:
        ANT_PATH: ant
      run: ant test-javase
  
  build-mac-jdk11-nofx:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
    - name: "Install Ant"
      run: brew install ant
    - name: Build with Ant
      env:
        ANT_PATH: ant
      run: ant test-javase

  
